name = "PosterColorimetryAnalysis"
uuid = "56103546-8668-4453-a002-7338c783dc0d"
version = "0.1.0"
authors = ["Dyumes", "Caro-13", "Dav0105"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[compat]
CSV = "0.10.15"
ColorTypes = "0.12.1"
Colors = "0.13.1"
DataFrames = "1.8.1"
DelimitedFiles = "1.9.1"
FileIO = "1.17.1"
ImageShow = "0.3.8"
ImageTransformations = "0.10.2"
ImageView = "0.13.0"
Plots = "1.41.2"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.8"
TestImages = "1.9.0"
