name = "PosterColorimetryAnalysis"
uuid = "56103546-8668-4453-a002-7338c783dc0d"
authors = ["Dyumes", "Caro-13", "Dav0105"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
Colors = "0.13.1"
DataFrames = "1.8.1"
Plots = "1.41.2"
StatsBase = "0.34.8"
